from PySide6.QtCore import QCoreApplication,QMetaObject, QRect

from PySide6.QtWidgets import QComboBox, QLabel, QLineEdit, QMainWindow, QPushButton, QSizePolicy, QWidget, QSpinBox


class Ui_GsWindow(QMainWindow):
    def setupUi(self, GsWindow):
        if not GsWindow.objectName():
            GsWindow.setObjectName(u"GsWindow")
        GsWindow.resize(550, 137)
        self.centralwidget = QWidget(GsWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(24, 46, 67, 16))
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(339, 44, 67, 16))
        self.comboBox_3 = QComboBox(self.centralwidget)
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(405, 37, 106, 32))
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(16, 10, 106, 32))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(65, 107, 231, 16))
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(87, 73, 98, 21))
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy1)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(23, 76, 67, 16))
        self.btn_rename = QPushButton(self.centralwidget)
        self.btn_rename.setObjectName(u"btn_rename")
        self.btn_rename.setGeometry(QRect(465, 99, 70, 32))
        self.comboBox_2 = QComboBox(self.centralwidget)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(81, 39, 111, 32))
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(339, 73, 67, 16))
        self.pbn_openfd = QPushButton(self.centralwidget)
        self.pbn_openfd.setObjectName(u"pbn_openfd")
        self.pbn_openfd.setGeometry(QRect(337, 99, 97, 32))
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(25, 107, 31, 16))
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.spinBox = QSpinBox(self.centralwidget)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(410, 70, 96, 21))
        sizePolicy2 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy2)
        self.spinBox.setMaximum(40)
        GsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(GsWindow)

        QMetaObject.connectSlotsByName(GsWindow)

    # setupUi

    def retranslateUi(self, GsWindow):
        GsWindow.setWindowTitle(QCoreApplication.translate("GsWindow", u"MainWindow", None))
        self.label.setText(QCoreApplication.translate("GsWindow", u"\u540d\u79f0\u683c\u5f0f\uff1a", None))
        self.label_6.setText(QCoreApplication.translate("GsWindow", u"\u6570\u5b57\u4f4d\u7f6e\uff1a", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("GsWindow", u"\u540d\u79f0\u4e4b\u540e", None))
        self.comboBox_3.setItemText(1, QCoreApplication.translate("GsWindow", u"\u540d\u79f0\u4e4b\u524d", None))

        self.comboBox.setItemText(0, QCoreApplication.translate("GsWindow", u"\u683c\u5f0f", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("GsWindow", u"\u6dfb\u52a0\u6587\u672c", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("GsWindow", u"\u66ff\u6362\u6587\u672c", None))

        self.label_4.setText("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText(QCoreApplication.translate("GsWindow", u"\u6587\u4ef6", None))
        self.lineEdit.setPlaceholderText("")
        self.label_2.setText(QCoreApplication.translate("GsWindow", u"\u81ea\u5b9a\u540d\u79f0\uff1a", None))
        self.btn_rename.setText(QCoreApplication.translate("GsWindow", u"\u91cd\u547d\u540d", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("GsWindow", u"\u540d\u79f0\u548c\u7d22\u5f15", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("GsWindow", u"\u540d\u79f0\u548c\u8ba1\u6570", None))

        self.label_5.setText(QCoreApplication.translate("GsWindow", u"\u5f00\u59cb\u6570\u5b57\uff1a", None))
        self.pbn_openfd.setText(QCoreApplication.translate("GsWindow", u"\u9009\u62e9\u6587\u4ef6\u5939", None))
        self.label_3.setText(QCoreApplication.translate("GsWindow", u"\u793a\u4f8b:", None))
    # retranslateUi
